### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by Lniq** [foamliu/Tacotron2-CN#15]
Hi,foamLiu. Thanks for your pytorch implementation of Tacotron2! Could you please share the weight file？Thank you very much.

**Comment by zsl24** [comment]
The author has shared his model in [release](https://github.com/foamliu/Tacotron2-Mandarin/releases/download/v1.0/tacotron2-cn.pt).

**Comment by foamliu** [comment]
Thanks @zsl24
