### ISSUE TITLE
你好，请问下首页中的alignment结果是运行了多少步？

### ISSUE THREAD

**Issue by neoragex2002** [foamliu/Tacotron2-CN#7]
是不是至少100K以上才有这样的alignment效果？

**Comment by neoragex2002** [comment]
下图是训练了60K步(batch_size=64）的结果，使用的是本repo的默认参数。从结果看，从一开始alignment就没有学到有用信息，始终focus在头部帧和最后一帧。当valid loss达到0.3之后就再也下不去了。请问：本实现确认正确吗？学习率是否正确？需要多少steps才能达到readme.md中的对准？能否给个参照说明？

![image](https://user-images.githubusercontent.com/4516135/81033323-c00cfe80-8ec5-11ea-8abd-fdfa90b43c8d.png)

**Comment by HandsLing** [comment]
@neoragex2002 我也是从头训练过也是这样的结果，只有在作者给的模型上微调才可以

**Comment by foamliu** [comment]
maybe 100K-200K.
